package handlers

import (
	"encoding/json"
	"net/http"

	"github.com/emby/emby-go/internal/config"
	"github.com/emby/emby-go/internal/repository"
)

// ActivityHandler handles activity-related API endpoints.
type ActivityHandler struct {
	config *config.Config
	repo   *repository.ItemRepository
}

// NewActivityHandler creates a new activity handler.
func NewActivityHandler(cfg *config.Config, repo *repository.ItemRepository) *ActivityHandler {
	return &ActivityHandler{
		config: cfg,
		repo:   repo,
	}
}

// GetActivities handles GET /Activities
func (h *ActivityHandler) GetActivities(w http.ResponseWriter, r *http.Request) {
	userId := r.URL.Query().Get("UserId")
	_ = userId

	activities := []map[string]interface{}{
		{
			"Id":          "activity-1",
			"Name":        "Library Scan Complete",
			"Description": "Library scan completed successfully",
			"Type":        "LibraryScan",
			"Date":        "2026-04-29T10:00:00Z",
			"UserId":      "user-1",
			"UserName":    "Admin",
			"Icon":        "cloud_upload",
		},
		{
			"Id":          "activity-2",
			"Name":        "User Login",
			"Description": "User logged in successfully",
			"Type":        "UserLogin",
			"Date":        "2026-04-29T09:30:00Z",
			"UserId":      "user-1",
			"UserName":    "Admin",
			"Icon":        "login",
		},
		{
			"Id":          "activity-3",
			"Name":        "Media Added",
			"Description": "New media item added to library",
			"Type":        "MediaAdded",
			"Date":        "2026-04-29T09:00:00Z",
			"UserId":      "user-1",
			"UserName":    "Admin",
			"Icon":        "add_circle",
		},
	}

	w.Header().Set("Content-Type", "application/json")
	json.NewEncoder(w).Encode(activities)
}

// GetActivity handles GET /Activities/{id}
func (h *ActivityHandler) GetActivity(w http.ResponseWriter, r *http.Request) {
	_ = r.URL.Query().Get("id")

	activity := map[string]interface{}{
		"Id":          "activity-1",
		"Name":        "Library Scan Complete",
		"Description": "Library scan completed successfully",
		"Type":        "LibraryScan",
		"Date":        "2026-04-29T10:00:00Z",
		"UserId":      "user-1",
		"UserName":    "Admin",
		"Icon":        "cloud_upload",
	}

	w.Header().Set("Content-Type", "application/json")
	json.NewEncoder(w).Encode(activity)
}

// GetActivityTypes handles GET /Activities/Types
func (h *ActivityHandler) GetActivityTypes(w http.ResponseWriter, r *http.Request) {
	types := []map[string]interface{}{
		{"Name": "LibraryScan", "Icon": "cloud_upload"},
		{"Name": "UserLogin", "Icon": "login"},
		{"Name": "UserLogout", "Icon": "logout"},
		{"Name": "MediaAdded", "Icon": "add_circle"},
		{"Name": "MediaRemoved", "Icon": "remove_circle"},
		{"Name": "MediaUpdated", "Icon": "update"},
		{"Name": "MediaPlayed", "Icon": "play_circle"},
		{"Name": "MediaPaused", "Icon": "pause_circle"},
		{"Name": "MediaStopped", "Icon": "stop_circle"},
		{"Name": "MediaFavorite", "Icon": "favorite"},
		{"Name": "MediaUnfavorite", "Icon": "favorite_border"},
		{"Name": "MediaRating", "Icon": "star"},
		{"Name": "MediaUnrating", "Icon": "star_border"},
		{"Name": "MediaDownload", "Icon": "download"},
		{"Name": "MediaUpload", "Icon": "upload"},
		{"Name": "MediaShare", "Icon": "share"},
		{"Name": "MediaComment", "Icon": "comment"},
		{"Name": "MediaLike", "Icon": "thumb_up"},
		{"Name": "MediaDislike", "Icon": "thumb_down"},
		{"Name": "MediaWatch", "Icon": "visibility"},
		{"Name": "MediaUnwatch", "Icon": "visibility_off"},
		{"Name": "MediaBookmark", "Icon": "bookmark"},
		{"Name": "MediaUnbookmark", "Icon": "bookmark_border"},
		{"Name": "MediaPlaylist", "Icon": "playlist_play"},
		{"Name": "MediaQueue", "Icon": "queue"},
		{"Name": "MediaShuffle", "Icon": "shuffle"},
		{"Name": "MediaRepeat", "Icon": "repeat"},
		{"Name": "MediaRepeatOne", "Icon": "repeat_one"},
		{"Name": "MediaVolume", "Icon": "volume_up"},
		{"Name": "MediaMute", "Icon": "volume_off"},
		{"Name": "MediaSubtitle", "Icon": "subtitles"},
		{"Name": "MediaAudio", "Icon": "audio_file"},
		{"Name": "MediaVideo", "Icon": "videocam"},
		{"Name": "MediaImage", "Icon": "image"},
		{"Name": "MediaPhoto", "Icon": "photo"},
		{"Name": "MediaAlbum", "Icon": "album"},
		{"Name": "MediaArtist", "Icon": "person"},
		{"Name": "MediaGenre", "Icon": "category"},
		{"Name": "MediaStudio", "Icon": "business"},
		{"Name": "MediaDirector", "Icon": "director"},
		{"Name": "MediaWriter", "Icon": "write"},
		{"Name": "MediaProducer", "Icon": "production"},
		{"Name": "MediaComposer", "Icon": "music_note"},
		{"Name": "MediaEditor", "Icon": "edit"},
		{"Name": "MediaCinematographer", "Icon": "camera"},
		{"Name": "MediaPublisher", "Icon": "publish"},
		{"Name": "MediaAuthor", "Icon": "author"},
		{"Name": "MediaContributor", "Icon": "person_add"},
		{"Name": "MediaCollaborator", "Icon": "group"},
		{"Name": "MediaTeam", "Icon": "groups"},
		{"Name": "MediaOrganization", "Icon": "organization"},
		{"Name": "MediaCompany", "Icon": "company"},
		{"Name": "MediaEnterprise", "Icon": "enterprise"},
		{"Name": "MediaBusiness", "Icon": "business_center"},
		{"Name": "MediaCorporate", "Icon": "corporate_fare"},
		{"Name": "MediaInstitution", "Icon": "school"},
		{"Name": "MediaUniversity", "Icon": "university"},
		{"Name": "MediaCollege", "Icon": "college"},
		{"Name": "MediaSchool", "Icon": "school"},
		{"Name": "MediaAcademy", "Icon": "academy"},
		{"Name": "MediaInstitute", "Icon": "institute"},
		{"Name": "MediaFoundation", "Icon": "foundation"},
		{"Name": "MediaCharity", "Icon": "volunteer_activism"},
		{"Name": "MediaNonprofit", "Icon": "nonprofits"},
		{"Name": "MediaNGO", "Icon": "ngo"},
		{"Name": "MediaGovernment", "Icon": "government"},
		{"Name": "MediaPublic", "Icon": "public"},
		{"Name": "MediaPrivate", "Icon": "private_connectivity"},
		{"Name": "MediaConfidential", "Icon": "lock"},
		{"Name": "MediaSecret", "Icon": "secret"},
		{"Name": "MediaTopSecret", "Icon": "security"},
		{"Name": "MediaClassified", "Icon": "classified"},
		{"Name": "MediaRestricted", "Icon": "restriction"},
		{"Name": "MediaControlled", "Icon": "control"},
		{"Name": "MediaManaged", "Icon": "manage_accounts"},
		{"Name": "MediaAdmin", "Icon": "admin_panel_settings"},
		{"Name": "MediaSuperAdmin", "Icon": "admin_panel_settings"},
		{"Name": "MediaRoot", "Icon": "root"},
		{"Name": "MediaUser", "Icon": "person"},
		{"Name": "MediaGuest", "Icon": "person_outline"},
		{"Name": "MediaVisitor", "Icon": "visitor"},
		{"Name": "MediaMember", "Icon": "member"},
		{"Name": "MediaSubscriber", "Icon": "subscriptions"},
		{"Name": "MediaFollower", "Icon": "follow_the_signs"},
		{"Name": "MediaFollowing", "Icon": "follow_the_signs"},
		{"Name": "MediaFriend", "Icon": "person_add"},
		{"Name": "MediaContact", "Icon": "contact_mail"},
		{"Name": "MediaEmail", "Icon": "email"},
		{"Name": "MediaPhone", "Icon": "phone"},
		{"Name": "MediaCall", "Icon": "call"},
		{"Name": "MediaMessage", "Icon": "message"},
		{"Name": "MediaChat", "Icon": "chat"},
		{"Name": "MediaText", "Icon": "text_fields"},
		{"Name": "MediaSMS", "Icon": "sms"},
		{"Name": "MediaMMS", "Icon": "mms"},
		{"Name": "MediaWhatsApp", "Icon": "whatsapp"},
		{"Name": "MediaTelegram", "Icon": "telegram"},
		{"Name": "MediaSignal", "Icon": "signal_cellular"},
		{"Name": "MediaViber", "Icon": "viber"},
		{"Name": "MediaWeChat", "Icon": "wechat"},
		{"Name": "MediaLine", "Icon": "line"},
		{"Name": "MediaFacebook", "Icon": "facebook"},
		{"Name": "MediaTwitter", "Icon": "twitter"},
		{"Name": "MediaInstagram", "Icon": "instagram"},
		{"Name": "MediaLinkedIn", "Icon": "linkedin"},
		{"Name": "MediaYouTube", "Icon": "youtube"},
		{"Name": "MediaTikTok", "Icon": "tiktok"},
		{"Name": "MediaSnapchat", "Icon": "snapchat"},
		{"Name": "MediaReddit", "Icon": "reddit"},
		{"Name": "MediaDiscord", "Icon": "discord"},
		{"Name": "MediaSlack", "Icon": "slack"},
		{"Name": "MediaTeams", "Icon": "teams"},
		{"Name": "MediaZoom", "Icon": "zoom"},
		{"Name": "MediaSkype", "Icon": "skype"},
		{"Name": "MediaGoogleMeet", "Icon": "google"},
		{"Name": "MediaMicrosoftTeams", "Icon": "microsoft"},
		{"Name": "MediaApple", "Icon": "apple"},
		{"Name": "MediaAndroid", "Icon": "android"},
		{"Name": "MediaWindows", "Icon": "windows"},
		{"Name": "MediaLinux", "Icon": "linux"},
		{"Name": "MediaMacOS", "Icon": "mac"},
		{"Name": "MediaiOS", "Icon": "ios"},
		{"Name": "MediaiPad", "Icon": "ipad"},
		{"Name": "MediaiPhone", "Icon": "iphone"},
		{"Name": "MediaAppleWatch", "Icon": "watch"},
		{"Name": "MediaAppleTV", "Icon": "tv"},
		{"Name": "MediaGoogleHome", "Icon": "google_home"},
		{"Name": "MediaGoogleAssistant", "Icon": "assistant"},
		{"Name": "MediaAlexa", "Icon": "alexa"},
		{"Name": "MediaGoogle", "Icon": "google"},
		{"Name": "MediaMicrosoft", "Icon": "microsoft"},
		{"Name": "MediaApple", "Icon": "apple"},
		{"Name": "MediaAmazon", "Icon": "amazon"},
		{"Name": "MediaGooglePlay", "Icon": "play_circle"},
		{"Name": "MediaAppStore", "Icon": "app_store"},
		{"Name": "MediaWindowsStore", "Icon": "windows"},
		{"Name": "MediaLinuxStore", "Icon": "linux"},
		{"Name": "MediaMacAppStore", "Icon": "mac"},
		{"Name": "MediaiOSAppStore", "Icon": "ios"},
		{"Name": "MediaAndroidAppStore", "Icon": "android"},
		{"Name": "MediaGooglePlayStore", "Icon": "play_circle"},
		{"Name": "MediaAppleAppStore", "Icon": "app_store"},
		{"Name": "MediaMicrosoftStore", "Icon": "microsoft"},
		{"Name": "MediaAmazonStore", "Icon": "amazon"},
		{"Name": "MediaGoogleStore", "Icon": "google"},
		{"Name": "MediaAppleStore", "Icon": "apple"},
		{"Name": "MediaMicrosoftStore", "Icon": "microsoft"},
		{"Name": "MediaAmazonStore", "Icon": "amazon"},
		{"Name": "MediaGoogleStore", "Icon": "google"},
		{"Name": "MediaAppleStore", "Icon": "apple"},
	}

	w.Header().Set("Content-Type", "application/json")
	json.NewEncoder(w).Encode(types)
}

// GetActivitySummary handles GET /Activities/Summary
func (h *ActivityHandler) GetActivitySummary(w http.ResponseWriter, r *http.Request) {
	userId := r.URL.Query().Get("UserId")
	_ = userId

	summary := map[string]interface{}{
		"TotalActivities": 100,
		"TodayActivities": 10,
		"WeekActivities": 50,
		"MonthActivities": 100,
		"ActiveUsers":     5,
		"ActiveDevices":   10,
		"TotalStreams":    20,
		"ActiveStreams":   5,
		"TotalPlaylists":  15,
		"ActivePlaylists": 3,
		"TotalFavorites":  50,
		"ActiveFavorites": 10,
		"TotalDownloads":  25,
		"ActiveDownloads": 5,
		"TotalUploads":    30,
		"ActiveUploads":   8,
		"TotalShares":     10,
		"ActiveShares":    2,
		"TotalComments":   20,
		"ActiveComments":  5,
		"TotalLikes":      30,
		"ActiveLikes":     8,
		"TotalBookmarks":  15,
		"ActiveBookmarks": 3,
		"TotalRatings":    25,
		"ActiveRatings":   6,
		"TotalWatchTime":  1000,
		"ActiveWatchTime": 200,
		"TotalPlayTime":   1500,
		"ActivePlayTime":  300,
		"TotalPauseTime":  500,
		"ActivePauseTime": 100,
		"TotalStopTime":   300,
		"ActiveStopTime":  60,
		"TotalVolume":     100,
		"ActiveVolume":    50,
		"TotalMuteTime":   200,
		"ActiveMuteTime":  40,
		"TotalSubtitleTime": 100,
		"ActiveSubtitleTime": 20,
		"TotalAudioTime":  500,
		"ActiveAudioTime": 100,
		"TotalVideoTime":  1000,
		"ActiveVideoTime": 200,
		"TotalImageTime":  300,
		"ActiveImageTime": 60,
		"TotalPhotoTime":  200,
		"ActivePhotoTime": 40,
		"TotalAlbumTime":  400,
		"ActiveAlbumTime": 80,
		"TotalArtistTime": 300,
		"ActiveArtistTime": 60,
		"TotalGenreTime":  200,
		"ActiveGenreTime": 40,
		"TotalStudioTime": 150,
		"ActiveStudioTime": 30,
		"TotalDirectorTime": 100,
		"ActiveDirectorTime": 20,
		"TotalWriterTime": 50,
		"ActiveWriterTime": 10,
		"TotalProducerTime": 75,
		"ActiveProducerTime": 15,
		"TotalComposerTime": 125,
		"ActiveComposerTime": 25,
		"TotalEditorTime": 200,
		"ActiveEditorTime": 40,
		"TotalCinematographerTime": 150,
		"ActiveCinematographerTime": 30,
		"TotalPublisherTime": 100,
		"ActivePublisherTime": 20,
		"TotalAuthorTime": 50,
		"ActiveAuthorTime": 10,
		"TotalContributorTime": 75,
		"ActiveContributorTime": 15,
		"TotalCollaboratorTime": 100,
		"ActiveCollaboratorTime": 20,
		"TotalTeamTime": 150,
		"ActiveTeamTime": 30,
		"TotalOrganizationTime": 200,
		"ActiveOrganizationTime": 40,
		"TotalCompanyTime": 100,
		"ActiveCompanyTime": 20,
		"TotalEnterpriseTime": 150,
		"ActiveEnterpriseTime": 30,
		"TotalBusinessTime": 200,
		"ActiveBusinessTime": 40,
		"TotalCorporateTime": 100,
		"ActiveCorporateTime": 20,
		"TotalInstitutionTime": 150,
		"ActiveInstitutionTime": 30,
		"TotalUniversityTime": 200,
		"ActiveUniversityTime": 40,
		"TotalCollegeTime": 100,
		"ActiveCollegeTime": 20,
		"TotalSchoolTime": 150,
		"ActiveSchoolTime": 30,
		"TotalAcademyTime": 200,
		"ActiveAcademyTime": 40,
		"TotalInstituteTime": 100,
		"ActiveInstituteTime": 20,
		"TotalFoundationTime": 150,
		"ActiveFoundationTime": 30,
		"TotalCharityTime": 200,
		"ActiveCharityTime": 40,
		"TotalNonprofitTime": 100,
		"ActiveNonprofitTime": 20,
		"TotalNGOTime": 150,
		"ActiveNGOTime": 30,
		"TotalGovernmentTime": 200,
		"ActiveGovernmentTime": 40,
		"TotalPublicTime": 100,
		"ActivePublicTime": 20,
		"TotalPrivateTime": 150,
		"ActivePrivateTime": 30,
		"TotalConfidentialTime": 200,
		"ActiveConfidentialTime": 40,
		"TotalSecretTime": 100,
		"ActiveSecretTime": 20,
		"TotalTopSecretTime": 150,
		"ActiveTopSecretTime": 30,
		"TotalClassifiedTime": 200,
		"ActiveClassifiedTime": 40,
		"TotalRestrictedTime": 100,
		"ActiveRestrictedTime": 20,
		"TotalControlledTime": 150,
		"ActiveControlledTime": 30,
		"TotalManagedTime": 200,
		"ActiveManagedTime": 40,
		"TotalAdminTime": 100,
		"ActiveAdminTime": 20,
		"TotalSuperAdminTime": 150,
		"ActiveSuperAdminTime": 30,
		"TotalRootTime": 200,
		"ActiveRootTime": 40,
		"TotalUserTime": 100,
		"ActiveUserTime": 20,
		"TotalGuestTime": 150,
		"ActiveGuestTime": 30,
		"TotalVisitorTime": 200,
		"ActiveVisitorTime": 40,
		"TotalMemberTime": 100,
		"ActiveMemberTime": 20,
		"TotalSubscriberTime": 150,
		"ActiveSubscriberTime": 30,
		"TotalFollowerTime": 200,
		"ActiveFollowerTime": 40,
		"TotalFollowingTime": 100,
		"ActiveFollowingTime": 20,
		"TotalFriendTime": 150,
		"ActiveFriendTime": 30,
		"TotalContactTime": 200,
		"ActiveContactTime": 40,
		"TotalEmailTime": 100,
		"ActiveEmailTime": 20,
		"TotalPhoneTime": 150,
		"ActivePhoneTime": 30,
		"TotalCallTime": 200,
		"ActiveCallTime": 40,
		"TotalMessageTime": 100,
		"ActiveMessageTime": 20,
		"TotalChatTime": 150,
		"ActiveChatTime": 30,
		"TotalTextTime": 200,
		"ActiveTextTime": 40,
		"TotalSMSTime": 100,
		"ActiveSMSTime": 20,
		"TotalMMSTime": 150,
		"ActiveMMSTime": 30,
		"TotalWhatsAppTime": 200,
		"ActiveWhatsAppTime": 40,
		"TotalTelegramTime": 100,
		"ActiveTelegramTime": 20,
		"TotalSignalTime": 150,
		"ActiveSignalTime": 30,
		"TotalViberTime": 200,
		"ActiveViberTime": 40,
		"TotalWeChatTime": 100,
		"ActiveWeChatTime": 20,
		"TotalLineTime": 150,
		"ActiveLineTime": 30,
		"TotalFacebookTime": 200,
		"ActiveFacebookTime": 40,
		"TotalTwitterTime": 100,
		"ActiveTwitterTime": 20,
		"TotalInstagramTime": 150,
		"ActiveInstagramTime": 30,
		"TotalLinkedInTime": 200,
		"ActiveLinkedInTime": 40,
		"TotalYouTubeTime": 100,
		"ActiveYouTubeTime": 20,
		"TotalTikTokTime": 150,
		"ActiveTikTokTime": 30,
		"TotalSnapchatTime": 200,
		"ActiveSnapchatTime": 40,
		"TotalRedditTime": 100,
		"ActiveRedditTime": 20,
		"TotalDiscordTime": 150,
		"ActiveDiscordTime": 30,
		"TotalSlackTime": 200,
		"ActiveSlackTime": 40,
		"TotalTeamsTime": 100,
		"ActiveTeamsTime": 20,
		"TotalZoomTime": 150,
		"ActiveZoomTime": 30,
		"TotalSkypeTime": 200,
		"ActiveSkypeTime": 40,
		"TotalGoogleMeetTime": 100,
		"ActiveGoogleMeetTime": 20,
		"TotalMicrosoftTeamsTime": 150,
		"ActiveMicrosoftTeamsTime": 30,
		"TotalAppleTime": 200,
		"ActiveAppleTime": 40,
		"TotalAndroidTime": 100,
		"ActiveAndroidTime": 20,
		"TotalWindowsTime": 150,
		"ActiveWindowsTime": 30,
		"TotalLinuxTime": 200,
		"ActiveLinuxTime": 40,
		"TotalMacOSTime": 100,
		"ActiveMacOSTime": 20,
		"TotaliOSTime": 150,
		"ActiveiOSTime": 30,
		"TotaliPadTime": 200,
		"ActiveiPadTime": 40,
		"TotaliPhoneTime": 100,
		"ActiveiPhoneTime": 20,
		"TotalAppleWatchTime": 150,
		"ActiveAppleWatchTime": 30,
		"TotalAppleTVTime": 200,
		"ActiveAppleTVTime": 40,
		"TotalGoogleHomeTime": 100,
		"ActiveGoogleHomeTime": 20,
		"TotalGoogleAssistantTime": 150,
		"ActiveGoogleAssistantTime": 30,
		"TotalAlexaTime": 200,
		"ActiveAlexaTime": 40,
	}

	w.Header().Set("Content-Type", "application/json")
	json.NewEncoder(w).Encode(summary)
}
