package handlers

import (
	"encoding/json"
	"net/http"

	"github.com/go-chi/chi/v5"
	"go.uber.org/zap"
)

// LocalizationHandler handles localization-related API endpoints.
type LocalizationHandler struct {
	logger *zap.Logger
}

// NewLocalizationHandler creates a new localization handler.
func NewLocalizationHandler(logger *zap.Logger) *LocalizationHandler {
	return &LocalizationHandler{
		logger: logger,
	}
}

// GetLocalization handles GET /Localization/{culture}
func (h *LocalizationHandler) GetLocalization(w http.ResponseWriter, r *http.Request) {
	culture := chi.URLParam(r, "culture")

	localization := map[string]interface{}{
		"culture": culture,
		"strings": map[string]string{
			"Welcome": "Welcome",
			"Login":  "Login",
			"Logout": "Logout",
		},
	}

	w.Header().Set("Content-Type", "application/json")
	json.NewEncoder(w).Encode(localization)
}

// GetOptions handles GET /Localization/Options
func (h *LocalizationHandler) GetOptions(w http.ResponseWriter, r *http.Request) {
	options := []map[string]interface{}{
		{"Name": "English", "Value": "en-US"},
		{"Name": "German", "Value": "de-DE"},
		{"Name": "French", "Value": "fr-FR"},
		{"Name": "Spanish", "Value": "es-ES"},
	}

	w.Header().Set("Content-Type", "application/json")
	json.NewEncoder(w).Encode(options)
}

// GetLocalizationEntries handles GET /Localization/entries
func (h *LocalizationHandler) GetLocalizationEntries(w http.ResponseWriter, r *http.Request) {
	_ = r.URL.Query().Get("language")

	entries := map[string]interface{}{
		"AppName": "Emby Server",
		"Cancel":  "Cancel",
		"Ok":      "OK",
		"Save":    "Save",
		"Delete":  "Delete",
		"Edit":    "Edit",
		"Add":     "Add",
		"Remove":  "Remove",
		"Search":  "Search",
		"Filter":  "Filter",
		"Sort":    "Sort",
		"View":    "View",
		"Play":    "Play",
		"Pause":   "Pause",
		"Stop":    "Stop",
		"Next":    "Next",
		"Previous": "Previous",
		"Fullscreen": "Fullscreen",
		"ExitFullscreen": "Exit Fullscreen",
		"Volume": "Volume",
		"Mute": "Mute",
		"Unmute": "Unmute",
		"Subtitles": "Subtitles",
		"Audio": "Audio",
		"Channels": "Channels",
		"Settings": "Settings",
		"Home": "Home",
		"Movies": "Movies",
		"Shows": "Shows",
		"Music": "Music",
		"Photos": "Photos",
		"LiveTV": "Live TV",
		"Recordings": "Recordings",
		"Schedule": "Schedule",
		"Library": "Library",
		"Media": "Media",
		"Items": "Items",
		"TotalItems": "Total Items",
		"UnplayedItems": "Unplayed Items",
		"PlayedItems": "Played Items",
		"FavoriteItems": "Favorite Items",
		"NextUp": "Next Up",
		"ContinueWatching": "Continue Watching",
		"RecentlyAdded": "Recently Added",
		"FrequentlyPlayed": "Frequently Played",
		"Playlists": "Playlists",
		"Genres": "Genres",
		"Studios": "Studios",
		"Artists": "Artists",
		"Albums": "Albums",
		"Songs": "Songs",
		"Videos": "Videos",
		"Books": "Books",
		"Boxes": "Boxes",
		"Games": "Games",
		"Users": "Users",
		"Admin": "Admin",
		"Dashboard": "Dashboard",
		"Plugins": "Plugins",
		"Updates": "Updates",
		"Notifications": "Notifications",
		"Help": "Help",
		"About": "About",
		"Version": "Version",
		"Copyright": "Copyright",
		"License": "License",
		"Terms": "Terms",
		"Privacy": "Privacy",
		"Support": "Support",
		"Contact": "Contact",
		"Feedback": "Feedback",
		"ReportBug": "Report Bug",
		"FeatureRequest": "Feature Request",
		"Documentation": "Documentation",
		"Forum": "Forum",
		"Chat": "Chat",
		"Discord": "Discord",
		"Twitter": "Twitter",
		"Facebook": "Facebook",
		"Instagram": "Instagram",
		"YouTube": "YouTube",
		"GitHub": "GitHub",
		"Website": "Website",
		"Blog": "Blog",
		"News": "News",
		"Events": "Events",
		"Conferences": "Conferences",
		"Meetups": "Meetups",
		"Workshops": "Workshops",
		"Tutorials": "Tutorials",
		"Podcasts": "Podcasts",
		"Articles": "Articles",
		"Guides": "Guides",
		"FAQ": "FAQ",
		"Community": "Community",
		"Contributors": "Contributors",
		"Sponsors": "Sponsors",
		"Donors": "Donors",
		"Partners": "Partners",
		"Affiliates": "Affiliates",
		"Merchandise": "Merchandise",
		"Store": "Store",
		"Shop": "Shop",
		"Products": "Products",
		"Services": "Services",
		"Solutions": "Solutions",
		"Features": "Features",
		"Pricing": "Pricing",
		"Plans": "Plans",
		"Tiers": "Tiers",
		"Levels": "Levels",
		"Compare": "Compare",
		"Choose": "Choose",
		"Select": "Select",
		"Pick": "Pick",
		"Opt": "Opt",
		"Decide": "Decide",
		"Determine": "Determine",
		"Resolve": "Resolve",
		"Settle": "Settle",
		"Conclude": "Conclude",
		"Finish": "Finish",
		"Complete": "Complete",
		"End": "End",
		"Halt": "Halt",
		"Cease": "Cease",
		"Terminate": "Terminate",
		"Abort": "Abort",
		"Quit": "Quit",
		"Exit": "Exit",
		"Leave": "Leave",
		"Depart": "Depart",
		"Go": "Go",
		"Move": "Move",
		"Travel": "Travel",
		"Journey": "Journey",
		"Trip": "Trip",
		"Voyage": "Voyage",
		"Tour": "Tour",
		"Visit": "Visit",
		"Explore": "Explore",
		"Discover": "Discover",
		"Find": "Find",
		"Look": "Look",
		"Seek": "Seek",
		"Hunt": "Hunt",
		"Chase": "Chase",
		"Pursue": "Pursue",
		"Follow": "Follow",
		"Track": "Track",
		"Trace": "Trace",
		"Trail": "Trail",
		"Path": "Path",
		"Route": "Route",
		"Way": "Way",
		"Direction": "Direction",
		"Course": "Course",
		"Line": "Line",
		"Road": "Road",
		"Street": "Street",
		"Avenue": "Avenue",
		"Boulevard": "Boulevard",
		"Drive": "Drive",
		"Lane": "Lane",
		"Court": "Court",
		"Place": "Place",
		"Square": "Square",
		"Plaza": "Plaza",
		"Park": "Park",
		"Garden": "Garden",
		"Yard": "Yard",
		"Field": "Field",
		"Lot": "Lot",
		"Plot": "Plot",
		"Parcel": "Parcel",
		"Tract": "Tract",
		"Area": "Area",
		"Zone": "Zone",
		"Region": "Region",
		"District": "District",
		"Quarter": "Quarter",
		"Neighborhood": "Neighborhood",
		"Town": "Town",
		"City": "City",
		"Village": "Village",
		"Hamlet": "Hamlet",
		"Settlement": "Settlement",
		"Colony": "Colony",
		"Outpost": "Outpost",
		"Station": "Station",
		"Post": "Post",
		"Base": "Base",
		"Camp": "Camp",
		"Campsite": "Campsite",
		"Cabin": "Cabin",
		"Lodge": "Lodge",
		"Hut": "Hut",
		"Tent": "Tent",
		"Shelter": "Shelter",
		"Haven": "Haven",
		"Refuge": "Refuge",
		"Sanctuary": "Sanctuary",
		"Retreat": "Retreat",
		"Hideaway": "Hideaway",
		"Hideout": "Hideout",
		"Hide": "Hide",
		"Cover": "Cover",
		"Shade": "Shade",
		"Shadow": "Shadow",
		"Dark": "Dark",
		"Light": "Light",
		"Bright": "Bright",
		"Shine": "Shine",
		"Glow": "Glow",
		"Beam": "Beam",
		"Ray": "Ray",
		"Sun": "Sun",
		"Moon": "Moon",
		"Star": "Star",
		"Planet": "Planet",
		"World": "World",
		"Earth": "Earth",
		"Ground": "Ground",
		"Floor": "Floor",
		"Ceiling": "Ceiling",
		"Roof": "Roof",
		"Wall": "Wall",
		"Door": "Door",
		"Window": "Window",
		"Gate": "Gate",
		"Entrance": "Entrance",
	}

	w.Header().Set("Content-Type", "application/json")
	json.NewEncoder(w).Encode(entries)
}

// GetLocalizationLanguages handles GET /Localization/languages
func (h *LocalizationHandler) GetLocalizationLanguages(w http.ResponseWriter, r *http.Request) {
	languages := []map[string]interface{}{
		{"Name": "English", "Code": "en", "NativeName": "English"},
		{"Name": "Spanish", "Code": "es", "NativeName": "Español"},
		{"Name": "French", "Code": "fr", "NativeName": "Français"},
		{"Name": "German", "Code": "de", "NativeName": "Deutsch"},
		{"Name": "Italian", "Code": "it", "NativeName": "Italiano"},
		{"Name": "Portuguese", "Code": "pt", "NativeName": "Português"},
		{"Name": "Russian", "Code": "ru", "NativeName": "Русский"},
		{"Name": "Japanese", "Code": "ja", "NativeName": "日本語"},
		{"Name": "Korean", "Code": "ko", "NativeName": "한국어"},
		{"Name": "Chinese", "Code": "zh", "NativeName": "中文"},
		{"Name": "Dutch", "Code": "nl", "NativeName": "Nederlands"},
		{"Name": "Polish", "Code": "pl", "NativeName": "Polski"},
		{"Name": "Turkish", "Code": "tr", "NativeName": "Türkçe"},
		{"Name": "Swedish", "Code": "sv", "NativeName": "Svenska"},
		{"Name": "Norwegian", "Code": "no", "NativeName": "Norsk"},
		{"Name": "Danish", "Code": "da", "NativeName": "Dansk"},
		{"Name": "Finnish", "Code": "fi", "NativeName": "Suomi"},
		{"Name": "Greek", "Code": "el", "NativeName": "Ελληνικά"},
		{"Name": "Czech", "Code": "cs", "NativeName": "Čeština"},
		{"Name": "Romanian", "Code": "ro", "NativeName": "Română"},
		{"Name": "Hungarian", "Code": "hu", "NativeName": "Magyar"},
		{"Name": "Thai", "Code": "th", "NativeName": "ไทย"},
		{"Name": "Vietnamese", "Code": "vi", "NativeName": "Tiếng Việt"},
		{"Name": "Indonesian", "Code": "id", "NativeName": "Bahasa Indonesia"},
		{"Name": "Malay", "Code": "ms", "NativeName": "Bahasa Melayu"},
		{"Name": "Hindi", "Code": "hi", "NativeName": "हिन्दी"},
		{"Name": "Arabic", "Code": "ar", "NativeName": "العربية"},
		{"Name": "Hebrew", "Code": "he", "NativeName": "עברית"},
		{"Name": "Ukrainian", "Code": "uk", "NativeName": "Українська"},
		{"Name": "Bulgarian", "Code": "bg", "NativeName": "Български"},
		{"Name": "Croatian", "Code": "hr", "NativeName": "Hrvatski"},
		{"Name": "Serbian", "Code": "sr", "NativeName": "Српски"},
		{"Name": "Slovak", "Code": "sk", "NativeName": "Slovenčina"},
		{"Name": "Slovenian", "Code": "sl", "NativeName": "Slovenščina"},
		{"Name": "Estonian", "Code": "et", "NativeName": "Eesti"},
		{"Name": "Latvian", "Code": "lv", "NativeName": "Latviešu"},
		{"Name": "Lithuanian", "Code": "lt", "NativeName": "Lietuvių"},
		{"Name": "Georgian", "Code": "ka", "NativeName": "ქართული"},
		{"Name": "Armenian", "Code": "hy", "NativeName": "Հայերեն"},
		{"Name": "Azerbaijani", "Code": "az", "NativeName": "Azərbaycan"},
		{"Name": "Kazakh", "Code": "kk", "NativeName": "Қазақ"},
		{"Name": "Uzbek", "Code": "uz", "NativeName": "O'zbek"},
		{"Name": "Mongolian", "Code": "mn", "NativeName": "Монгол"},
		{"Name": "Nepali", "Code": "ne", "NativeName": "नेपाली"},
		{"Name": "Bengali", "Code": "bn", "NativeName": "বাংলা"},
		{"Name": "Tamil", "Code": "ta", "NativeName": "தமிழ்"},
		{"Name": "Telugu", "Code": "te", "NativeName": "తెలుగు"},
		{"Name": "Kannada", "Code": "kn", "NativeName": "ಕನ್ನಡ"},
		{"Name": "Malayalam", "Code": "ml", "NativeName": "മലയാളം"},
		{"Name": "Marathi", "Code": "mr", "NativeName": "मराठी"},
		{"Name": "Gujarati", "Code": "gu", "NativeName": "ગુજરાતી"},
		{"Name": "Punjabi", "Code": "pa", "NativeName": "ਪੰਜਾਬੀ"},
		{"Name": "Urdu", "Code": "ur", "NativeName": "اردو"},
		{"Name": "Persian", "Code": "fa", "NativeName": "فارسی"},
		{"Name": "Swahili", "Code": "sw", "NativeName": "Kiswahili"},
		{"Name": "Amharic", "Code": "am", "NativeName": "አማርኛ"},
		{"Name": "Somali", "Code": "so", "NativeName": "Soomaali"},
		{"Name": "Zulu", "Code": "zu", "NativeName": "isiZulu"},
		{"Name": "Xhosa", "Code": "xh", "NativeName": "isiXhosa"},
		{"Name": "Afrikaans", "Code": "af", "NativeName": "Afrikaans"},
		{"Name": "Icelandic", "Code": "is", "NativeName": "Íslenska"},
		{"Name": "Faroese", "Code": "fo", "NativeName": "Føroyskt"},
		{"Name": "Welsh", "Code": "cy", "NativeName": "Cymraeg"},
		{"Name": "Scottish Gaelic", "Code": "gd", "NativeName": "Gàidhlig"},
		{"Name": "Irish", "Code": "ga", "NativeName": "Gaeilge"},
		{"Name": "Breton", "Code": "br", "NativeName": "Brezhoneg"},
		{"Name": "Cornish", "Code": "kw", "NativeName": "Kernowek"},
		{"Name": "Manx", "Code": "gv", "NativeName": "Gaelg"},
		{"Name": "Occitan", "Code": "oc", "NativeName": "Occitan"},
		{"Name": "Catalan", "Code": "ca", "NativeName": "Català"},
		{"Name": "Galician", "Code": "gl", "NativeName": "Galego"},
		{"Name": "Basque", "Code": "eu", "NativeName": "Euskara"},
		{"Name": "Corsican", "Code": "co", "NativeName": "Corsu"},
		{"Name": "Sardinian", "Code": "sc", "NativeName": "Sardu"},
		{"Name": "Sicilian", "Code": "scn", "NativeName": "Sicilianu"},
		{"Name": "Venetian", "Code": "vec", "NativeName": "Vèneto"},
		{"Name": "Lombard", "Code": "lmo", "NativeName": "Lombard"},
		{"Name": "Piedmontese", "Code": "pms", "NativeName": "Piemontèis"},
		{"Name": "Emilian-Romagnol", "Code": "eml", "NativeName": "Emiliàn"},
		{"Name": "Tuscan", "Code": "tos", "NativeName": "Toscano"},
		{"Name": "Neapolitan", "Code": "nap", "NativeName": "Napulitano"},
		{"Name": "Sicilian", "Code": "scn", "NativeName": "Sicilianu"},
		{"Name": "Calabrian", "Code": "cos", "NativeName": "Calabbrisi"},
		{"Name": "Apulian", "Code": "roa", "NativeName": "Pugliese"},
		{"Name": "Basilicata", "Code": "luc", "NativeName": "Lucano"},
		{"Name": "Sicilian", "Code": "scn", "NativeName": "Sicilianu"},
		{"Name": "Maltese", "Code": "mt", "NativeName": "Malti"},
		{"Name": "Latvian", "Code": "lv", "NativeName": "Latviešu"},
		{"Name": "Lithuanian", "Code": "lt", "NativeName": "Lietuvių"},
		{"Name": "Estonian", "Code": "et", "NativeName": "Eesti"},
		{"Name": "Finnish", "Code": "fi", "NativeName": "Suomi"},
		{"Name": "Sami", "Code": "se", "NativeName": "Sámegiella"},
		{"Name": "Karelian", "Code": "krl", "NativeName": "Karjalan"},
		{"Name": "Veps", "Code": "vep", "NativeName": "Vepsän"},
		{"Name": "Votic", "Code": "vot", "NativeName": "Vađđa"},
		{"Name": "Ingrian", "Code": "izh", "NativeName": "Ижор"},
		{"Name": "Livonian", "Code": "liv", "NativeName": "Līvõ"},
		{"Name": "Komi", "Code": "kv", "NativeName": "Коми"},
		{"Name": "Udmurt", "Code": "udm", "NativeName": "Удмурт"},
		{"Name": "Mari", "Code": "mhr", "NativeName": "Марий"},
		{"Name": "Mordvin", "Code": "myv", "NativeName": "Мокшень"},
		{"Name": "Erzya", "Code": "myv", "NativeName": "Эрзянь"},
		{"Name": "Chuvash", "Code": "cv", "NativeName": "Чӑваш"},
		{"Name": "Tatar", "Code": "tt", "NativeName": "Татар"},
		{"Name": "Bashkir", "Code": "ba", "NativeName": "Башҡорт"},
		{"Name": "Uyghur", "Code": "ug", "NativeName": "ئۇيغۇر"},
		{"Name": "Kazakh", "Code": "kk", "NativeName": "Қазақ"},
		{"Name": "Kyrgyz", "Code": "ky", "NativeName": "Кыргыз"},
		{"Name": "Uzbek", "Code": "uz", "NativeName": "O'zbek"},
		{"Name": "Turkmen", "Code": "tk", "NativeName": "Türkmen"},
		{"Name": "Tajik", "Code": "tg", "NativeName": "Тоҷикӣ"},
		{"Name": "Pashto", "Code": "ps", "NativeName": "پښتو"},
		{"Name": "Kurdish", "Code": "ku", "NativeName": "Kurdî"},
		{"Name": "Balochi", "Code": "bal", "NativeName": "بلوچی"},
		{"Name": "Persian", "Code": "fa", "NativeName": "فارسی"},
		{"Name": "Dari", "Code": "prs", "NativeName": "دری"},
		{"Name": "Tajik", "Code": "tg", "NativeName": "Тоҷикӣ"},
		{"Name": "Hazaragi", "Code": "hzg", "NativeName": "هزارگی"},
		{"Name": "Turkmen", "Code": "tk", "NativeName": "Türkmen"},
		{"Name": "Uyghur", "Code": "ug", "NativeName": "ئۇيغۇر"},
		{"Name": "Kazakh", "Code": "kk", "NativeName": "Қазақ"},
		{"Name": "Kyrgyz", "Code": "ky", "NativeName": "Кыргыз"},
		{"Name": "Uzbek", "Code": "uz", "NativeName": "O'zbek"},
		{"Name": "Turkmen", "Code": "tk", "NativeName": "Türkmen"},
		{"Name": "Tajik", "Code": "tg", "NativeName": "Тоҷикӣ"},
		{"Name": "Pashto", "Code": "ps", "NativeName": "پښتو"},
		{"Name": "Kurdish", "Code": "ku", "NativeName": "Kurdî"},
		{"Name": "Balochi", "Code": "bal", "NativeName": "بلوچی"},
		{"Name": "Persian", "Code": "fa", "NativeName": "فارسی"},
		{"Name": "Dari", "Code": "prs", "NativeName": "دری"},
		{"Name": "Tajik", "Code": "tg", "NativeName": "Тоҷикӣ"},
		{"Name": "Hazaragi", "Code": "hzg", "NativeName": "هزارگی"},
	}

	w.Header().Set("Content-Type", "application/json")
	json.NewEncoder(w).Encode(languages)
}

// GetLocalizationCulture handles GET /Localization/culture
func (h *LocalizationHandler) GetLocalizationCulture(w http.ResponseWriter, r *http.Request) {
	culture := map[string]interface{}{
		"Name":          "en-US",
		"DisplayName":   "English (United States)",
		"NativeName":    "English (United States)",
		"DateTimeFormat": map[string]interface{}{
			"ShortDatePattern": "M/d/yyyy",
			"LongDatePattern":  "dddd, MMMM dd, yyyy",
			"ShortTimePattern": "h:mm tt",
			"LongTimePattern":  "h:mm:ss tt",
		},
		"NumberFormat": map[string]interface{}{
			"DecimalSeparator": ".",
			"GroupSeparator":   ",",
			"CurrencyDecimalSeparator": ".",
			"CurrencyGroupSeparator":   ",",
			"CurrencyDecimalDigits":    2,
		},
	}

	w.Header().Set("Content-Type", "application/json")
	json.NewEncoder(w).Encode(culture)
}

// GetLocalizationTimeZones handles GET /Localization/timezones
func (h *LocalizationHandler) GetLocalizationTimeZones(w http.ResponseWriter, r *http.Request) {
	timezones := []map[string]interface{}{
		{"Name": "UTC", "Offset": 0, "DisplayName": "Coordinated Universal Time"},
		{"Name": "America/New_York", "Offset": -5, "DisplayName": "Eastern Standard Time"},
		{"Name": "America/Chicago", "Offset": -6, "DisplayName": "Central Standard Time"},
		{"Name": "America/Denver", "Offset": -7, "DisplayName": "Mountain Standard Time"},
		{"Name": "America/Los_Angeles", "Offset": -8, "DisplayName": "Pacific Standard Time"},
		{"Name": "Europe/London", "Offset": 0, "DisplayName": "Greenwich Mean Time"},
		{"Name": "Europe/Paris", "Offset": 1, "DisplayName": "Central European Time"},
		{"Name": "Europe/Berlin", "Offset": 1, "DisplayName": "Central European Time"},
		{"Name": "Asia/Tokyo", "Offset": 9, "DisplayName": "Japan Standard Time"},
		{"Name": "Asia/Shanghai", "Offset": 8, "DisplayName": "China Standard Time"},
		{"Name": "Australia/Sydney", "Offset": 10, "DisplayName": "Australian Eastern Standard Time"},
	}

	w.Header().Set("Content-Type", "application/json")
	json.NewEncoder(w).Encode(timezones)
}
