package handlers

import (
	"encoding/json"
	"net/http"

	"github.com/go-chi/chi/v5"
	"go.uber.org/zap"
)

// LocalizationHandler handles localization-related API endpoints.
type LocalizationHandler struct {
	logger *zap.Logger
}

// NewLocalizationHandler creates a new localization handler.
func NewLocalizationHandler(logger *zap.Logger) *LocalizationHandler {
	return &LocalizationHandler{
		logger: logger,
	}
}

// GetLocalization handles GET /Localization/{culture}
func (h *LocalizationHandler) GetLocalization(w http.ResponseWriter, r *http.Request) {
	culture := chi.URLParam(r, "culture")

	localization := map[string]interface{}{
		"culture": culture,
		"strings": map[string]string{
			"Welcome": "Welcome",
			"Login":  "Login",
			"Logout": "Logout",
		},
	}

	w.Header().Set("Content-Type", "application/json")
	json.NewEncoder(w).Encode(localization)
}

func (h *LocalizationHandler) GetCultures(w http.ResponseWriter, r *http.Request) {
	cultures := []map[string]interface{}{
		{"DisplayName": "English", "TwoLetterISOLanguageName": "en", "ThreeLetterISOLanguageName": "eng", "NativeName": "English"},
		{"DisplayName": "Arabic", "TwoLetterISOLanguageName": "ar", "ThreeLetterISOLanguageName": "ara", "NativeName": "العربية"},
		{"DisplayName": "Belarusian", "TwoLetterISOLanguageName": "be", "ThreeLetterISOLanguageName": "bel", "NativeName": "Беларуская"},
		{"DisplayName": "Bulgarian", "TwoLetterISOLanguageName": "bg", "ThreeLetterISOLanguageName": "bul", "NativeName": "Български"},
		{"DisplayName": "Catalan", "TwoLetterISOLanguageName": "ca", "ThreeLetterISOLanguageName": "cat", "NativeName": "Català"},
		{"DisplayName": "Chinese (Simplified)", "TwoLetterISOLanguageName": "zh-CN", "ThreeLetterISOLanguageName": "zho", "NativeName": "简体中文"},
		{"DisplayName": "Chinese (Traditional)", "TwoLetterISOLanguageName": "zh-TW", "ThreeLetterISOLanguageName": "zho", "NativeName": "繁體中文"},
		{"DisplayName": "Czech", "TwoLetterISOLanguageName": "cs", "ThreeLetterISOLanguageName": "ces", "NativeName": "Čeština"},
		{"DisplayName": "Danish", "TwoLetterISOLanguageName": "da", "ThreeLetterISOLanguageName": "dan", "NativeName": "Dansk"},
		{"DisplayName": "Dutch", "TwoLetterISOLanguageName": "nl", "ThreeLetterISOLanguageName": "nld", "NativeName": "Nederlands"},
		{"DisplayName": "Finnish", "TwoLetterISOLanguageName": "fi", "ThreeLetterISOLanguageName": "fin", "NativeName": "Suomi"},
		{"DisplayName": "French", "TwoLetterISOLanguageName": "fr", "ThreeLetterISOLanguageName": "fra", "NativeName": "Français"},
		{"DisplayName": "German", "TwoLetterISOLanguageName": "de", "ThreeLetterISOLanguageName": "deu", "NativeName": "Deutsch"},
		{"DisplayName": "Greek", "TwoLetterISOLanguageName": "el", "ThreeLetterISOLanguageName": "ell", "NativeName": "Ελληνικά"},
		{"DisplayName": "Hebrew", "TwoLetterISOLanguageName": "he", "ThreeLetterISOLanguageName": "heb", "NativeName": "עברית"},
		{"DisplayName": "Hindi", "TwoLetterISOLanguageName": "hi", "ThreeLetterISOLanguageName": "hin", "NativeName": "हिन्दी"},
		{"DisplayName": "Hungarian", "TwoLetterISOLanguageName": "hu", "ThreeLetterISOLanguageName": "hun", "NativeName": "Magyar"},
		{"DisplayName": "Indonesian", "TwoLetterISOLanguageName": "id", "ThreeLetterISOLanguageName": "ind", "NativeName": "Bahasa Indonesia"},
		{"DisplayName": "Italian", "TwoLetterISOLanguageName": "it", "ThreeLetterISOLanguageName": "ita", "NativeName": "Italiano"},
		{"DisplayName": "Japanese", "TwoLetterISOLanguageName": "ja", "ThreeLetterISOLanguageName": "jpn", "NativeName": "日本語"},
		{"DisplayName": "Korean", "TwoLetterISOLanguageName": "ko", "ThreeLetterISOLanguageName": "kor", "NativeName": "한국어"},
		{"DisplayName": "Norwegian", "TwoLetterISOLanguageName": "nb", "ThreeLetterISOLanguageName": "nor", "NativeName": "Norsk"},
		{"DisplayName": "Polish", "TwoLetterISOLanguageName": "pl", "ThreeLetterISOLanguageName": "pol", "NativeName": "Polski"},
		{"DisplayName": "Portuguese (Brazil)", "TwoLetterISOLanguageName": "pt-BR", "ThreeLetterISOLanguageName": "por", "NativeName": "Português (Brasil)"},
		{"DisplayName": "Portuguese (Portugal)", "TwoLetterISOLanguageName": "pt-PT", "ThreeLetterISOLanguageName": "por", "NativeName": "Português"},
		{"DisplayName": "Romanian", "TwoLetterISOLanguageName": "ro", "ThreeLetterISOLanguageName": "ron", "NativeName": "Română"},
		{"DisplayName": "Russian", "TwoLetterISOLanguageName": "ru", "ThreeLetterISOLanguageName": "rus", "NativeName": "Русский"},
		{"DisplayName": "Slovak", "TwoLetterISOLanguageName": "sk", "ThreeLetterISOLanguageName": "slk", "NativeName": "Slovenčina"},
		{"DisplayName": "Spanish", "TwoLetterISOLanguageName": "es", "ThreeLetterISOLanguageName": "spa", "NativeName": "Español"},
		{"DisplayName": "Swedish", "TwoLetterISOLanguageName": "sv", "ThreeLetterISOLanguageName": "swe", "NativeName": "Svenska"},
		{"DisplayName": "Thai", "TwoLetterISOLanguageName": "th", "ThreeLetterISOLanguageName": "tha", "NativeName": "ไทย"},
		{"DisplayName": "Turkish", "TwoLetterISOLanguageName": "tr", "ThreeLetterISOLanguageName": "tur", "NativeName": "Türkçe"},
		{"DisplayName": "Ukrainian", "TwoLetterISOLanguageName": "uk", "ThreeLetterISOLanguageName": "ukr", "NativeName": "Українська"},
		{"DisplayName": "Vietnamese", "TwoLetterISOLanguageName": "vi", "ThreeLetterISOLanguageName": "vie", "NativeName": "Tiếng Việt"},
	}

	w.Header().Set("Content-Type", "application/json")
	json.NewEncoder(w).Encode(cultures)
}

func (h *LocalizationHandler) GetCountries(w http.ResponseWriter, r *http.Request) {
	countries := []map[string]interface{}{
		{"DisplayName": "Afghanistan", "TwoLetterISORegionName": "AF", "ThreeLetterISORegionName": "AFG"},
		{"DisplayName": "Albania", "TwoLetterISORegionName": "AL", "ThreeLetterISORegionName": "ALB"},
		{"DisplayName": "Algeria", "TwoLetterISORegionName": "DZ", "ThreeLetterISORegionName": "DZA"},
		{"DisplayName": "Argentina", "TwoLetterISORegionName": "AR", "ThreeLetterISORegionName": "ARG"},
		{"DisplayName": "Australia", "TwoLetterISORegionName": "AU", "ThreeLetterISORegionName": "AUS"},
		{"DisplayName": "Austria", "TwoLetterISORegionName": "AT", "ThreeLetterISORegionName": "AUT"},
		{"DisplayName": "Bangladesh", "TwoLetterISORegionName": "BD", "ThreeLetterISORegionName": "BGD"},
		{"DisplayName": "Belgium", "TwoLetterISORegionName": "BE", "ThreeLetterISORegionName": "BEL"},
		{"DisplayName": "Brazil", "TwoLetterISORegionName": "BR", "ThreeLetterISORegionName": "BRA"},
		{"DisplayName": "Canada", "TwoLetterISORegionName": "CA", "ThreeLetterISORegionName": "CAN"},
		{"DisplayName": "Chile", "TwoLetterISORegionName": "CL", "ThreeLetterISORegionName": "CHL"},
		{"DisplayName": "China", "TwoLetterISORegionName": "CN", "ThreeLetterISORegionName": "CHN"},
		{"DisplayName": "Colombia", "TwoLetterISORegionName": "CO", "ThreeLetterISORegionName": "COL"},
		{"DisplayName": "Croatia", "TwoLetterISORegionName": "HR", "ThreeLetterISORegionName": "HRV"},
		{"DisplayName": "Czech Republic", "TwoLetterISORegionName": "CZ", "ThreeLetterISORegionName": "CZE"},
		{"DisplayName": "Denmark", "TwoLetterISORegionName": "DK", "ThreeLetterISORegionName": "DNK"},
		{"DisplayName": "Egypt", "TwoLetterISORegionName": "EG", "ThreeLetterISORegionName": "EGY"},
		{"DisplayName": "Finland", "TwoLetterISORegionName": "FI", "ThreeLetterISORegionName": "FIN"},
		{"DisplayName": "France", "TwoLetterISORegionName": "FR", "ThreeLetterISORegionName": "FRA"},
		{"DisplayName": "Germany", "TwoLetterISORegionName": "DE", "ThreeLetterISORegionName": "DEU"},
		{"DisplayName": "Greece", "TwoLetterISORegionName": "GR", "ThreeLetterISORegionName": "GRC"},
		{"DisplayName": "Hong Kong", "TwoLetterISORegionName": "HK", "ThreeLetterISORegionName": "HKG"},
		{"DisplayName": "Hungary", "TwoLetterISORegionName": "HU", "ThreeLetterISORegionName": "HUN"},
		{"DisplayName": "India", "TwoLetterISORegionName": "IN", "ThreeLetterISORegionName": "IND"},
		{"DisplayName": "Indonesia", "TwoLetterISORegionName": "ID", "ThreeLetterISORegionName": "IDN"},
		{"DisplayName": "Ireland", "TwoLetterISORegionName": "IE", "ThreeLetterISORegionName": "IRL"},
		{"DisplayName": "Israel", "TwoLetterISORegionName": "IL", "ThreeLetterISORegionName": "ISR"},
		{"DisplayName": "Italy", "TwoLetterISORegionName": "IT", "ThreeLetterISORegionName": "ITA"},
		{"DisplayName": "Japan", "TwoLetterISORegionName": "JP", "ThreeLetterISORegionName": "JPN"},
		{"DisplayName": "Malaysia", "TwoLetterISORegionName": "MY", "ThreeLetterISORegionName": "MYS"},
		{"DisplayName": "Mexico", "TwoLetterISORegionName": "MX", "ThreeLetterISORegionName": "MEX"},
		{"DisplayName": "Netherlands", "TwoLetterISORegionName": "NL", "ThreeLetterISORegionName": "NLD"},
		{"DisplayName": "New Zealand", "TwoLetterISORegionName": "NZ", "ThreeLetterISORegionName": "NZL"},
		{"DisplayName": "Nigeria", "TwoLetterISORegionName": "NG", "ThreeLetterISORegionName": "NGA"},
		{"DisplayName": "Norway", "TwoLetterISORegionName": "NO", "ThreeLetterISORegionName": "NOR"},
		{"DisplayName": "Pakistan", "TwoLetterISORegionName": "PK", "ThreeLetterISORegionName": "PAK"},
		{"DisplayName": "Philippines", "TwoLetterISORegionName": "PH", "ThreeLetterISORegionName": "PHL"},
		{"DisplayName": "Poland", "TwoLetterISORegionName": "PL", "ThreeLetterISORegionName": "POL"},
		{"DisplayName": "Portugal", "TwoLetterISORegionName": "PT", "ThreeLetterISORegionName": "PRT"},
		{"DisplayName": "Romania", "TwoLetterISORegionName": "RO", "ThreeLetterISORegionName": "ROU"},
		{"DisplayName": "Russia", "TwoLetterISORegionName": "RU", "ThreeLetterISORegionName": "RUS"},
		{"DisplayName": "Saudi Arabia", "TwoLetterISORegionName": "SA", "ThreeLetterISORegionName": "SAU"},
		{"DisplayName": "Singapore", "TwoLetterISORegionName": "SG", "ThreeLetterISORegionName": "SGP"},
		{"DisplayName": "Slovakia", "TwoLetterISORegionName": "SK", "ThreeLetterISORegionName": "SVK"},
		{"DisplayName": "South Africa", "TwoLetterISORegionName": "ZA", "ThreeLetterISORegionName": "ZAF"},
		{"DisplayName": "South Korea", "TwoLetterISORegionName": "KR", "ThreeLetterISORegionName": "KOR"},
		{"DisplayName": "Spain", "TwoLetterISORegionName": "ES", "ThreeLetterISORegionName": "ESP"},
		{"DisplayName": "Sweden", "TwoLetterISORegionName": "SE", "ThreeLetterISORegionName": "SWE"},
		{"DisplayName": "Switzerland", "TwoLetterISORegionName": "CH", "ThreeLetterISORegionName": "CHE"},
		{"DisplayName": "Taiwan", "TwoLetterISORegionName": "TW", "ThreeLetterISORegionName": "TWN"},
		{"DisplayName": "Thailand", "TwoLetterISORegionName": "TH", "ThreeLetterISORegionName": "THA"},
		{"DisplayName": "Turkey", "TwoLetterISORegionName": "TR", "ThreeLetterISORegionName": "TUR"},
		{"DisplayName": "Ukraine", "TwoLetterISORegionName": "UA", "ThreeLetterISORegionName": "UKR"},
		{"DisplayName": "United Arab Emirates", "TwoLetterISORegionName": "AE", "ThreeLetterISORegionName": "ARE"},
		{"DisplayName": "United Kingdom", "TwoLetterISORegionName": "GB", "ThreeLetterISORegionName": "GBR"},
		{"DisplayName": "United States", "TwoLetterISORegionName": "US", "ThreeLetterISORegionName": "USA"},
		{"DisplayName": "Vietnam", "TwoLetterISORegionName": "VN", "ThreeLetterISORegionName": "VNM"},
	}

	w.Header().Set("Content-Type", "application/json")
	json.NewEncoder(w).Encode(countries)
}

func (h *LocalizationHandler) GetParentalRatings(w http.ResponseWriter, r *http.Request) {
	ratings := []map[string]interface{}{
		{"Name": "Australia", "Categories": []map[string]interface{}{
			{"Name": "G", "MaxLevel": 1, "Name2": "G"},
			{"Name": "PG", "MaxLevel": 2, "Name2": "Parental Guidance"},
			{"Name": "M", "MaxLevel": 3, "Name2": "M"},
			{"Name": "MA15+", "MaxLevel": 4, "Name2": "MA15+"},
			{"Name": "R18+", "MaxLevel": 5, "Name2": "R18+"},
		}},
		{"Name": "Canada", "Categories": []map[string]interface{}{
			{"Name": "G", "MaxLevel": 1, "Name2": "General"},
			{"Name": "PG", "MaxLevel": 2, "Name2": "Parental Guidance"},
			{"Name": "14+", "MaxLevel": 3, "Name2": "14+"},
			{"Name": "18+", "MaxLevel": 4, "Name2": "18+"},
			{"Name": "R", "MaxLevel": 5, "Name2": "Restricted"},
		}},
		{"Name": "Germany", "Categories": []map[string]interface{}{
			{"Name": "FSK 0", "MaxLevel": 1, "Name2": "Freigegeben ohne Altersbeschränkung"},
			{"Name": "FSK 6", "MaxLevel": 2, "Name2": "Freigegeben ab 6 Jahren"},
			{"Name": "FSK 12", "MaxLevel": 3, "Name2": "Freigegeben ab 12 Jahren"},
			{"Name": "FSK 16", "MaxLevel": 4, "Name2": "Freigegeben ab 16 Jahren"},
			{"Name": "FSK 18", "MaxLevel": 5, "Name2": "Keine Freigabe unter 18 Jahren"},
		}},
		{"Name": "United Kingdom", "Categories": []map[string]interface{}{
			{"Name": "U", "MaxLevel": 1, "Name2": "Universal"},
			{"Name": "PG", "MaxLevel": 2, "Name2": "Parental Guidance"},
			{"Name": "12A", "MaxLevel": 3, "Name2": "12A"},
			{"Name": "15", "MaxLevel": 4, "Name2": "15"},
			{"Name": "18", "MaxLevel": 5, "Name2": "18"},
		}},
		{"Name": "United States", "Categories": []map[string]interface{}{
			{"Name": "G", "MaxLevel": 1, "Name2": "General Audiences"},
			{"Name": "PG", "MaxLevel": 2, "Name2": "Parental Guidance Suggested"},
			{"Name": "PG-13", "MaxLevel": 3, "Name2": "Parents Strongly Cautioned"},
			{"Name": "R", "MaxLevel": 4, "Name2": "Restricted"},
			{"Name": "NC-17", "MaxLevel": 5, "Name2": "No One 17 and Under Admitted"},
		}},
	}

	w.Header().Set("Content-Type", "application/json")
	json.NewEncoder(w).Encode(ratings)
}

func (h *LocalizationHandler) GetOptions(w http.ResponseWriter, r *http.Request) {
	options := []map[string]interface{}{
		{"Name": "English", "Value": "en"},
		{"Name": "Arabic", "Value": "ar"},
		{"Name": "Belarusian", "Value": "be-BY"},
		{"Name": "Bulgarian", "Value": "bg-BG"},
		{"Name": "Catalan", "Value": "ca"},
		{"Name": "Chinese (Simplified)", "Value": "zh-CN"},
		{"Name": "Chinese (Traditional)", "Value": "zh-TW"},
		{"Name": "Czech", "Value": "cs"},
		{"Name": "Danish", "Value": "da"},
		{"Name": "Dutch", "Value": "nl"},
		{"Name": "Finnish", "Value": "fi"},
		{"Name": "French", "Value": "fr"},
		{"Name": "German", "Value": "de"},
		{"Name": "Greek", "Value": "el"},
		{"Name": "Hebrew", "Value": "he"},
		{"Name": "Hindi", "Value": "hi-IN"},
		{"Name": "Hungarian", "Value": "hu"},
		{"Name": "Indonesian", "Value": "id"},
		{"Name": "Italian", "Value": "it"},
		{"Name": "Japanese", "Value": "ja"},
		{"Name": "Korean", "Value": "ko"},
		{"Name": "Norwegian", "Value": "nb"},
		{"Name": "Polish", "Value": "pl"},
		{"Name": "Portuguese (Brazil)", "Value": "pt-BR"},
		{"Name": "Portuguese (Portugal)", "Value": "pt-PT"},
		{"Name": "Romanian", "Value": "ro"},
		{"Name": "Russian", "Value": "ru"},
		{"Name": "Slovak", "Value": "sk"},
		{"Name": "Spanish", "Value": "es"},
		{"Name": "Swedish", "Value": "sv"},
		{"Name": "Thai", "Value": "th"},
		{"Name": "Turkish", "Value": "tr"},
		{"Name": "Ukrainian", "Value": "uk"},
		{"Name": "Vietnamese", "Value": "vi"},
	}

	w.Header().Set("Content-Type", "application/json")
	json.NewEncoder(w).Encode(options)
}

// GetLocalizationEntries handles GET /Localization/entries
func (h *LocalizationHandler) GetLocalizationEntries(w http.ResponseWriter, r *http.Request) {
	_ = r.URL.Query().Get("language")

	entries := map[string]interface{}{
		"AppName": "Emby Server",
		"Cancel":  "Cancel",
		"Ok":      "OK",
		"Save":    "Save",
		"Delete":  "Delete",
		"Edit":    "Edit",
		"Add":     "Add",
		"Remove":  "Remove",
		"Search":  "Search",
		"Filter":  "Filter",
		"Sort":    "Sort",
		"View":    "View",
		"Play":    "Play",
		"Pause":   "Pause",
		"Stop":    "Stop",
		"Next":    "Next",
		"Previous": "Previous",
		"Fullscreen": "Fullscreen",
		"ExitFullscreen": "Exit Fullscreen",
		"Volume": "Volume",
		"Mute": "Mute",
		"Unmute": "Unmute",
		"Subtitles": "Subtitles",
		"Audio": "Audio",
		"Channels": "Channels",
		"Settings": "Settings",
		"Home": "Home",
		"Movies": "Movies",
		"Shows": "Shows",
		"Music": "Music",
		"Photos": "Photos",
		"LiveTV": "Live TV",
		"Recordings": "Recordings",
		"Schedule": "Schedule",
		"Library": "Library",
		"Media": "Media",
		"Items": "Items",
		"TotalItems": "Total Items",
		"UnplayedItems": "Unplayed Items",
		"PlayedItems": "Played Items",
		"FavoriteItems": "Favorite Items",
		"NextUp": "Next Up",
		"ContinueWatching": "Continue Watching",
		"RecentlyAdded": "Recently Added",
		"FrequentlyPlayed": "Frequently Played",
		"Playlists": "Playlists",
		"Genres": "Genres",
		"Studios": "Studios",
		"Artists": "Artists",
		"Albums": "Albums",
		"Songs": "Songs",
		"Videos": "Videos",
		"Books": "Books",
		"Boxes": "Boxes",
		"Games": "Games",
		"Users": "Users",
		"Admin": "Admin",
		"Dashboard": "Dashboard",
		"Plugins": "Plugins",
		"Updates": "Updates",
		"Notifications": "Notifications",
		"Help": "Help",
		"About": "About",
		"Version": "Version",
		"Copyright": "Copyright",
		"License": "License",
		"Terms": "Terms",
		"Privacy": "Privacy",
		"Support": "Support",
		"Contact": "Contact",
		"Feedback": "Feedback",
		"ReportBug": "Report Bug",
		"FeatureRequest": "Feature Request",
		"Documentation": "Documentation",
		"Forum": "Forum",
		"Chat": "Chat",
		"Discord": "Discord",
		"Twitter": "Twitter",
		"Facebook": "Facebook",
		"Instagram": "Instagram",
		"YouTube": "YouTube",
		"GitHub": "GitHub",
		"Website": "Website",
		"Blog": "Blog",
		"News": "News",
		"Events": "Events",
		"Conferences": "Conferences",
		"Meetups": "Meetups",
		"Workshops": "Workshops",
		"Tutorials": "Tutorials",
		"Podcasts": "Podcasts",
		"Articles": "Articles",
		"Guides": "Guides",
		"FAQ": "FAQ",
		"Community": "Community",
		"Contributors": "Contributors",
		"Sponsors": "Sponsors",
		"Donors": "Donors",
		"Partners": "Partners",
		"Affiliates": "Affiliates",
		"Merchandise": "Merchandise",
		"Store": "Store",
		"Shop": "Shop",
		"Products": "Products",
		"Services": "Services",
		"Solutions": "Solutions",
		"Features": "Features",
		"Pricing": "Pricing",
		"Plans": "Plans",
		"Tiers": "Tiers",
		"Levels": "Levels",
		"Compare": "Compare",
		"Choose": "Choose",
		"Select": "Select",
		"Pick": "Pick",
		"Opt": "Opt",
		"Decide": "Decide",
		"Determine": "Determine",
		"Resolve": "Resolve",
		"Settle": "Settle",
		"Conclude": "Conclude",
		"Finish": "Finish",
		"Complete": "Complete",
		"End": "End",
		"Halt": "Halt",
		"Cease": "Cease",
		"Terminate": "Terminate",
		"Abort": "Abort",
		"Quit": "Quit",
		"Exit": "Exit",
		"Leave": "Leave",
		"Depart": "Depart",
		"Go": "Go",
		"Move": "Move",
		"Travel": "Travel",
		"Journey": "Journey",
		"Trip": "Trip",
		"Voyage": "Voyage",
		"Tour": "Tour",
		"Visit": "Visit",
		"Explore": "Explore",
		"Discover": "Discover",
		"Find": "Find",
		"Look": "Look",
		"Seek": "Seek",
		"Hunt": "Hunt",
		"Chase": "Chase",
		"Pursue": "Pursue",
		"Follow": "Follow",
		"Track": "Track",
		"Trace": "Trace",
		"Trail": "Trail",
		"Path": "Path",
		"Route": "Route",
		"Way": "Way",
		"Direction": "Direction",
		"Course": "Course",
		"Line": "Line",
		"Road": "Road",
		"Street": "Street",
		"Avenue": "Avenue",
		"Boulevard": "Boulevard",
		"Drive": "Drive",
		"Lane": "Lane",
		"Court": "Court",
		"Place": "Place",
		"Square": "Square",
		"Plaza": "Plaza",
		"Park": "Park",
		"Garden": "Garden",
		"Yard": "Yard",
		"Field": "Field",
		"Lot": "Lot",
		"Plot": "Plot",
		"Parcel": "Parcel",
		"Tract": "Tract",
		"Area": "Area",
		"Zone": "Zone",
		"Region": "Region",
		"District": "District",
		"Quarter": "Quarter",
		"Neighborhood": "Neighborhood",
		"Town": "Town",
		"City": "City",
		"Village": "Village",
		"Hamlet": "Hamlet",
		"Settlement": "Settlement",
		"Colony": "Colony",
		"Outpost": "Outpost",
		"Station": "Station",
		"Post": "Post",
		"Base": "Base",
		"Camp": "Camp",
		"Campsite": "Campsite",
		"Cabin": "Cabin",
		"Lodge": "Lodge",
		"Hut": "Hut",
		"Tent": "Tent",
		"Shelter": "Shelter",
		"Haven": "Haven",
		"Refuge": "Refuge",
		"Sanctuary": "Sanctuary",
		"Retreat": "Retreat",
		"Hideaway": "Hideaway",
		"Hideout": "Hideout",
		"Hide": "Hide",
		"Cover": "Cover",
		"Shade": "Shade",
		"Shadow": "Shadow",
		"Dark": "Dark",
		"Light": "Light",
		"Bright": "Bright",
		"Shine": "Shine",
		"Glow": "Glow",
		"Beam": "Beam",
		"Ray": "Ray",
		"Sun": "Sun",
		"Moon": "Moon",
		"Star": "Star",
		"Planet": "Planet",
		"World": "World",
		"Earth": "Earth",
		"Ground": "Ground",
		"Floor": "Floor",
		"Ceiling": "Ceiling",
		"Roof": "Roof",
		"Wall": "Wall",
		"Door": "Door",
		"Window": "Window",
		"Gate": "Gate",
		"Entrance": "Entrance",
	}

	w.Header().Set("Content-Type", "application/json")
	json.NewEncoder(w).Encode(entries)
}

// GetLocalizationLanguages handles GET /Localization/languages
func (h *LocalizationHandler) GetLocalizationLanguages(w http.ResponseWriter, r *http.Request) {
	languages := []map[string]interface{}{
		{"Name": "English", "Code": "en", "NativeName": "English"},
		{"Name": "Spanish", "Code": "es", "NativeName": "Español"},
		{"Name": "French", "Code": "fr", "NativeName": "Français"},
		{"Name": "German", "Code": "de", "NativeName": "Deutsch"},
		{"Name": "Italian", "Code": "it", "NativeName": "Italiano"},
		{"Name": "Portuguese", "Code": "pt", "NativeName": "Português"},
		{"Name": "Russian", "Code": "ru", "NativeName": "Русский"},
		{"Name": "Japanese", "Code": "ja", "NativeName": "日本語"},
		{"Name": "Korean", "Code": "ko", "NativeName": "한국어"},
		{"Name": "Chinese", "Code": "zh", "NativeName": "中文"},
		{"Name": "Dutch", "Code": "nl", "NativeName": "Nederlands"},
		{"Name": "Polish", "Code": "pl", "NativeName": "Polski"},
		{"Name": "Turkish", "Code": "tr", "NativeName": "Türkçe"},
		{"Name": "Swedish", "Code": "sv", "NativeName": "Svenska"},
		{"Name": "Norwegian", "Code": "no", "NativeName": "Norsk"},
		{"Name": "Danish", "Code": "da", "NativeName": "Dansk"},
		{"Name": "Finnish", "Code": "fi", "NativeName": "Suomi"},
		{"Name": "Greek", "Code": "el", "NativeName": "Ελληνικά"},
		{"Name": "Czech", "Code": "cs", "NativeName": "Čeština"},
		{"Name": "Romanian", "Code": "ro", "NativeName": "Română"},
		{"Name": "Hungarian", "Code": "hu", "NativeName": "Magyar"},
		{"Name": "Thai", "Code": "th", "NativeName": "ไทย"},
		{"Name": "Vietnamese", "Code": "vi", "NativeName": "Tiếng Việt"},
		{"Name": "Indonesian", "Code": "id", "NativeName": "Bahasa Indonesia"},
		{"Name": "Malay", "Code": "ms", "NativeName": "Bahasa Melayu"},
		{"Name": "Hindi", "Code": "hi", "NativeName": "हिन्दी"},
		{"Name": "Arabic", "Code": "ar", "NativeName": "العربية"},
		{"Name": "Hebrew", "Code": "he", "NativeName": "עברית"},
		{"Name": "Ukrainian", "Code": "uk", "NativeName": "Українська"},
		{"Name": "Bulgarian", "Code": "bg", "NativeName": "Български"},
		{"Name": "Croatian", "Code": "hr", "NativeName": "Hrvatski"},
		{"Name": "Serbian", "Code": "sr", "NativeName": "Српски"},
		{"Name": "Slovak", "Code": "sk", "NativeName": "Slovenčina"},
		{"Name": "Slovenian", "Code": "sl", "NativeName": "Slovenščina"},
		{"Name": "Estonian", "Code": "et", "NativeName": "Eesti"},
		{"Name": "Latvian", "Code": "lv", "NativeName": "Latviešu"},
		{"Name": "Lithuanian", "Code": "lt", "NativeName": "Lietuvių"},
		{"Name": "Georgian", "Code": "ka", "NativeName": "ქართული"},
		{"Name": "Armenian", "Code": "hy", "NativeName": "Հայերեն"},
		{"Name": "Azerbaijani", "Code": "az", "NativeName": "Azərbaycan"},
		{"Name": "Kazakh", "Code": "kk", "NativeName": "Қазақ"},
		{"Name": "Uzbek", "Code": "uz", "NativeName": "O'zbek"},
		{"Name": "Mongolian", "Code": "mn", "NativeName": "Монгол"},
		{"Name": "Nepali", "Code": "ne", "NativeName": "नेपाली"},
		{"Name": "Bengali", "Code": "bn", "NativeName": "বাংলা"},
		{"Name": "Tamil", "Code": "ta", "NativeName": "தமிழ்"},
		{"Name": "Telugu", "Code": "te", "NativeName": "తెలుగు"},
		{"Name": "Kannada", "Code": "kn", "NativeName": "ಕನ್ನಡ"},
		{"Name": "Malayalam", "Code": "ml", "NativeName": "മലയാളം"},
		{"Name": "Marathi", "Code": "mr", "NativeName": "मराठी"},
		{"Name": "Gujarati", "Code": "gu", "NativeName": "ગુજરાતી"},
		{"Name": "Punjabi", "Code": "pa", "NativeName": "ਪੰਜਾਬੀ"},
		{"Name": "Urdu", "Code": "ur", "NativeName": "اردو"},
		{"Name": "Persian", "Code": "fa", "NativeName": "فارسی"},
		{"Name": "Swahili", "Code": "sw", "NativeName": "Kiswahili"},
		{"Name": "Amharic", "Code": "am", "NativeName": "አማርኛ"},
		{"Name": "Somali", "Code": "so", "NativeName": "Soomaali"},
		{"Name": "Zulu", "Code": "zu", "NativeName": "isiZulu"},
		{"Name": "Xhosa", "Code": "xh", "NativeName": "isiXhosa"},
		{"Name": "Afrikaans", "Code": "af", "NativeName": "Afrikaans"},
		{"Name": "Icelandic", "Code": "is", "NativeName": "Íslenska"},
		{"Name": "Faroese", "Code": "fo", "NativeName": "Føroyskt"},
		{"Name": "Welsh", "Code": "cy", "NativeName": "Cymraeg"},
		{"Name": "Scottish Gaelic", "Code": "gd", "NativeName": "Gàidhlig"},
		{"Name": "Irish", "Code": "ga", "NativeName": "Gaeilge"},
		{"Name": "Breton", "Code": "br", "NativeName": "Brezhoneg"},
		{"Name": "Cornish", "Code": "kw", "NativeName": "Kernowek"},
		{"Name": "Manx", "Code": "gv", "NativeName": "Gaelg"},
		{"Name": "Occitan", "Code": "oc", "NativeName": "Occitan"},
		{"Name": "Catalan", "Code": "ca", "NativeName": "Català"},
		{"Name": "Galician", "Code": "gl", "NativeName": "Galego"},
		{"Name": "Basque", "Code": "eu", "NativeName": "Euskara"},
		{"Name": "Corsican", "Code": "co", "NativeName": "Corsu"},
		{"Name": "Sardinian", "Code": "sc", "NativeName": "Sardu"},
		{"Name": "Sicilian", "Code": "scn", "NativeName": "Sicilianu"},
		{"Name": "Venetian", "Code": "vec", "NativeName": "Vèneto"},
		{"Name": "Lombard", "Code": "lmo", "NativeName": "Lombard"},
		{"Name": "Piedmontese", "Code": "pms", "NativeName": "Piemontèis"},
		{"Name": "Emilian-Romagnol", "Code": "eml", "NativeName": "Emiliàn"},
		{"Name": "Tuscan", "Code": "tos", "NativeName": "Toscano"},
		{"Name": "Neapolitan", "Code": "nap", "NativeName": "Napulitano"},
		{"Name": "Sicilian", "Code": "scn", "NativeName": "Sicilianu"},
		{"Name": "Calabrian", "Code": "cos", "NativeName": "Calabbrisi"},
		{"Name": "Apulian", "Code": "roa", "NativeName": "Pugliese"},
		{"Name": "Basilicata", "Code": "luc", "NativeName": "Lucano"},
		{"Name": "Sicilian", "Code": "scn", "NativeName": "Sicilianu"},
		{"Name": "Maltese", "Code": "mt", "NativeName": "Malti"},
		{"Name": "Latvian", "Code": "lv", "NativeName": "Latviešu"},
		{"Name": "Lithuanian", "Code": "lt", "NativeName": "Lietuvių"},
		{"Name": "Estonian", "Code": "et", "NativeName": "Eesti"},
		{"Name": "Finnish", "Code": "fi", "NativeName": "Suomi"},
		{"Name": "Sami", "Code": "se", "NativeName": "Sámegiella"},
		{"Name": "Karelian", "Code": "krl", "NativeName": "Karjalan"},
		{"Name": "Veps", "Code": "vep", "NativeName": "Vepsän"},
		{"Name": "Votic", "Code": "vot", "NativeName": "Vađđa"},
		{"Name": "Ingrian", "Code": "izh", "NativeName": "Ижор"},
		{"Name": "Livonian", "Code": "liv", "NativeName": "Līvõ"},
		{"Name": "Komi", "Code": "kv", "NativeName": "Коми"},
		{"Name": "Udmurt", "Code": "udm", "NativeName": "Удмурт"},
		{"Name": "Mari", "Code": "mhr", "NativeName": "Марий"},
		{"Name": "Mordvin", "Code": "myv", "NativeName": "Мокшень"},
		{"Name": "Erzya", "Code": "myv", "NativeName": "Эрзянь"},
		{"Name": "Chuvash", "Code": "cv", "NativeName": "Чӑваш"},
		{"Name": "Tatar", "Code": "tt", "NativeName": "Татар"},
		{"Name": "Bashkir", "Code": "ba", "NativeName": "Башҡорт"},
		{"Name": "Uyghur", "Code": "ug", "NativeName": "ئۇيغۇر"},
		{"Name": "Kazakh", "Code": "kk", "NativeName": "Қазақ"},
		{"Name": "Kyrgyz", "Code": "ky", "NativeName": "Кыргыз"},
		{"Name": "Uzbek", "Code": "uz", "NativeName": "O'zbek"},
		{"Name": "Turkmen", "Code": "tk", "NativeName": "Türkmen"},
		{"Name": "Tajik", "Code": "tg", "NativeName": "Тоҷикӣ"},
		{"Name": "Pashto", "Code": "ps", "NativeName": "پښتو"},
		{"Name": "Kurdish", "Code": "ku", "NativeName": "Kurdî"},
		{"Name": "Balochi", "Code": "bal", "NativeName": "بلوچی"},
		{"Name": "Persian", "Code": "fa", "NativeName": "فارسی"},
		{"Name": "Dari", "Code": "prs", "NativeName": "دری"},
		{"Name": "Tajik", "Code": "tg", "NativeName": "Тоҷикӣ"},
		{"Name": "Hazaragi", "Code": "hzg", "NativeName": "هزارگی"},
		{"Name": "Turkmen", "Code": "tk", "NativeName": "Türkmen"},
		{"Name": "Uyghur", "Code": "ug", "NativeName": "ئۇيغۇر"},
		{"Name": "Kazakh", "Code": "kk", "NativeName": "Қазақ"},
		{"Name": "Kyrgyz", "Code": "ky", "NativeName": "Кыргыз"},
		{"Name": "Uzbek", "Code": "uz", "NativeName": "O'zbek"},
		{"Name": "Turkmen", "Code": "tk", "NativeName": "Türkmen"},
		{"Name": "Tajik", "Code": "tg", "NativeName": "Тоҷикӣ"},
		{"Name": "Pashto", "Code": "ps", "NativeName": "پښتو"},
		{"Name": "Kurdish", "Code": "ku", "NativeName": "Kurdî"},
		{"Name": "Balochi", "Code": "bal", "NativeName": "بلوچی"},
		{"Name": "Persian", "Code": "fa", "NativeName": "فارسی"},
		{"Name": "Dari", "Code": "prs", "NativeName": "دری"},
		{"Name": "Tajik", "Code": "tg", "NativeName": "Тоҷикӣ"},
		{"Name": "Hazaragi", "Code": "hzg", "NativeName": "هزارگی"},
	}

	w.Header().Set("Content-Type", "application/json")
	json.NewEncoder(w).Encode(languages)
}

// GetLocalizationCulture handles GET /Localization/culture
func (h *LocalizationHandler) GetLocalizationCulture(w http.ResponseWriter, r *http.Request) {
	culture := map[string]interface{}{
		"Name":          "en-US",
		"DisplayName":   "English (United States)",
		"NativeName":    "English (United States)",
		"DateTimeFormat": map[string]interface{}{
			"ShortDatePattern": "M/d/yyyy",
			"LongDatePattern":  "dddd, MMMM dd, yyyy",
			"ShortTimePattern": "h:mm tt",
			"LongTimePattern":  "h:mm:ss tt",
		},
		"NumberFormat": map[string]interface{}{
			"DecimalSeparator": ".",
			"GroupSeparator":   ",",
			"CurrencyDecimalSeparator": ".",
			"CurrencyGroupSeparator":   ",",
			"CurrencyDecimalDigits":    2,
		},
	}

	w.Header().Set("Content-Type", "application/json")
	json.NewEncoder(w).Encode(culture)
}

// GetLocalizationTimeZones handles GET /Localization/timezones
func (h *LocalizationHandler) GetLocalizationTimeZones(w http.ResponseWriter, r *http.Request) {
	timezones := []map[string]interface{}{
		{"Name": "UTC", "Offset": 0, "DisplayName": "Coordinated Universal Time"},
		{"Name": "America/New_York", "Offset": -5, "DisplayName": "Eastern Standard Time"},
		{"Name": "America/Chicago", "Offset": -6, "DisplayName": "Central Standard Time"},
		{"Name": "America/Denver", "Offset": -7, "DisplayName": "Mountain Standard Time"},
		{"Name": "America/Los_Angeles", "Offset": -8, "DisplayName": "Pacific Standard Time"},
		{"Name": "Europe/London", "Offset": 0, "DisplayName": "Greenwich Mean Time"},
		{"Name": "Europe/Paris", "Offset": 1, "DisplayName": "Central European Time"},
		{"Name": "Europe/Berlin", "Offset": 1, "DisplayName": "Central European Time"},
		{"Name": "Asia/Tokyo", "Offset": 9, "DisplayName": "Japan Standard Time"},
		{"Name": "Asia/Shanghai", "Offset": 8, "DisplayName": "China Standard Time"},
		{"Name": "Australia/Sydney", "Offset": 10, "DisplayName": "Australian Eastern Standard Time"},
	}

	w.Header().Set("Content-Type", "application/json")
	json.NewEncoder(w).Encode(timezones)
}
